In [1]:
import pandas as pd
import numpy as np

In [41]:
vector=np.array([1,2,3,4,5])
n=np.size(vector)


In [43]:
def alexandare(vector,argument):
    x=vector.copy()
    if(argument==False):
        for i in range(0,n,1):
            x[i]=vector[i]**(n-i-1)
    if(argument==True):
        for i in range(0,n,1):
            x[i]=vector[i]**i
    return np.matrix(x)
        

In [44]:
alexandare(vector,True)

matrix([[  1,   2,   9,  64, 625]])

In [45]:
alexandare(vector,False)

matrix([[1, 8, 9, 4, 1]])

In [51]:
def movingavg(array,window_size):
    n=np.size(array)
    size=n-window_size+1
    x=np.zeros(size)
    for i in range(0,size):
        for j in range(i,i+window_size):
            x[i]+=array[j]
        x[i]=x[i]/window_size
    return x

In [53]:
x=np.array([3,5,7,2,8,11,65,72,81,99,100,150])

In [54]:
movingavg(x,3)

array([  5.        ,   4.66666667,   5.66666667,   7.        ,
        28.        ,  49.33333333,  72.66666667,  84.        ,
        93.33333333, 116.33333333])